# Generated by Django 3.1.6 on 2021-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('id',)},
        ),
    ]
