# Generated by Django 3.1.6 on 2021-02-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_oredering_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('id',)},
        ),
    ]
