# Generated by Django 3.1.6 on 2021-02-23 14:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('rate', models.CharField(choices=[('5', 'EXCELLENT'), ('4', 'GREAT'), ('3', 'GOOD'), ('2', 'ACCEPTED'), ('1', 'POOR'), ('0', 'NOTRATED')], default='0', max_length=50)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 16, 13, 16, 556732))),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploaded_images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderder', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Pending'), (2, 'Shipping'), (3, 'Deliverd')], default=0)),
                ('user_commnet', models.TextField(blank=True, null=True)),
                ('order_num', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000)])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 16, 13, 16, 558731))),
                ('orderder', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=1000)),
                ('items', models.ManyToManyField(to='orders.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
