# Generated by Django 3.1.6 on 2021-02-24 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210224_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 12, 18, 13, 977171)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 12, 18, 13, 977171)),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.CharField(choices=[(5, 'EXCELLENT'), (4, 'GREAT'), (3, 'GOOD'), (2, 'ACCEPTED'), (1, 'POOR'), (0, 'NOTRATED')], default=0, max_length=12),
        ),
    ]
