# Generated by Django 3.1.6 on 2021-02-24 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210224_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderder',
            new_name='ordererd',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 1, 28, 422992)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 1, 28, 421993)),
        ),
    ]
