# Generated by Django 3.1.6 on 2021-02-24 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20210224_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderder_date',
            new_name='ordered_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 3, 41, 647551)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 3, 41, 646552)),
        ),
    ]
