# Generated by Django 3.1.6 on 2021-02-24 14:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210224_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 18, 47, 459416)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 18, 47, 459416)),
        ),
    ]
