# Generated by Django 3.1.6 on 2021-02-24 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20210224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 21, 38, 774878)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 21, 38, 774878)),
        ),
    ]
