# Generated by Django 3.1.6 on 2021-02-24 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20210224_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 22, 39, 569332), unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 22, 39, 567333)),
        ),
    ]
