# Generated by Django 3.1.6 on 2021-02-24 14:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20210224_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 38, 18, 928463)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.PositiveIntegerField(default=1000, unique=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 38, 18, 928463)),
        ),
    ]
