# Generated by Django 3.1.6 on 2021-03-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_auto_20210228_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderder',
            new_name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 11, 38, 690720)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 11, 38, 689720)),
        ),
    ]
