# Generated by Django 3.1.6 on 2021-03-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_auto_20210301_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 21, 44, 717710)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 21, 44, 717710)),
        ),
    ]
